name: cookbook
description: Jordyn's personal cookbook :)
version: 1.0.3+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  cloud_firestore: ^0.12.9+5
  provider: ^2.0.0
  image_picker: ^0.6.2+3
  cached_network_image: ^2.0.0-rc

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/no_image.jpg

  fonts:
    - family: Cairo-SemiBold
      fonts:
        - asset: assets/Cairo-SemiBold.ttf
    - family: Roboto Mono
      fonts:
        - asset: assets/RobotoMono-Regular.ttf
    - family: Montserrat Regular
      fonts:
        - asset: assets/Montserrat-Regular.ttf
    - family: Ropa Sans
      fonts:
        - asset: assets/RopaSans-Regular.ttf
    - family: Truckin
      fonts:
        - asset: assets/KeeponTruckin.ttf
    - family:  MenuIcons
      fonts:
       - asset: assets/MenuIcons.ttf
